'use strict';
(()=>{
 const $=id=>document.getElementById(id),stage=$('stage'),room=$('room'),canvas=$('embers'),ctx=canvas.getContext('2d');
 const saveKey='anju-protocol-progress-v1';
 function loadProgress(){try{const saved=JSON.parse(localStorage.getItem(saveKey));const state=saved?.state;if(!state||!Number.isInteger(state.house)||state.house<0||state.house>=Shelter.houses.length||!Number.isInteger(state.night)||state.night<1||state.night>6||!['night','day','end'].includes(state.phase)||!Number.isFinite(state.coins)||!Number.isFinite(state.food))return null;return saved;}catch{return null;}}
 const saved=loadProgress();
 let s=saved?Shelter.migrate(saved.state):Shelter.create(),floor=saved?.floor===2&&saved.state.house===2?2:1,area=saved?.area==='corridor'&&saved.state.house===3?'corridor':'room',entered=Boolean(saved),opening=false,busy=false,activeSpot=null,motion=!matchMedia('(prefers-reduced-motion: reduce)').matches,frame=0,last=0,flashTimer=0,toastTimer=0,assaultState=null,assaultTimeout=0,endingDismissed=false;
 let handsCleanup=null,holdCleanup=null,assisted=false,assaultFrame=0;
 const musicFile=s.house===3?'tower-music.m4a':s.house>0?'cabin-music.m4a':'first-night.m4a';
 const sounds=createShelterAudio({musicFile,musicDefault:true,onError:()=>{$('audioRetry').hidden=false;toast('点击“恢复环境音”继续播放。');}});
 function persist(){if(!entered)return;try{localStorage.setItem(saveKey,JSON.stringify({state:s,floor,area}));}catch{}}
 function restart(){if(!window.confirm('重新开始会清除当前进度。确定回到第一夜吗？'))return;try{localStorage.removeItem(saveKey);}catch{}location.reload();}
 const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));const preloads=new Map();
 function preload(file){if(!preloads.has(file)){const image=new Image();preloads.set(file,new Promise((resolve,reject)=>{image.onload=()=>resolve(image);image.onerror=()=>{preloads.delete(file);reject(new Error('图片未载入'));};image.src='assets/'+file;}));}return preloads.get(file);}
 const flashReady=Promise.allSettled(['bridge-v1.jpg','street-v1.jpg'].map(preload));['cabin-v2.jpg','villa-v1.jpg','villa-upstairs-v1.jpg','shack-v1.jpg','tower-v2.jpg','tower-corridor-v1.jpg'].forEach(f=>preload(f).catch(()=>{}));
 const inspector=createRoomInspector({stage,layer:$('exploreLayer'),hotspots:$('hotspots'),onInspect:inspect});
 const data={
  door:{title:'木门',first:'木门还没有固定。那块旧木板靠在墙边，窗外的脚步正在靠近。',day:'门外通向失守的街道。门锁完好，你听见路口传来断续的嘶吼。'},
  window:{title:'窗户',first:'玻璃外有血掌印。窗栓松动，丧尸的脸几乎贴上了玻璃。',day:'仔细看外面的抓痕和人影，再决定是否花时间加固。'},
  supplies:{title:'旧桌抽屉',first:'抽屉里似乎卡着一个扁扁的纸包。'},
  terminal:{title:'安居终端',day:'透明系统页在桌面亮起。金币、梦境回收与房屋升级都汇集在这里。'},
  workbench:{title:'加固工具',day:'木板、铁钉和一卷胶带。你可以用今天的时间加固安全屋。'},
  fire:{title:'壁炉',day:'火光照亮了门窗接缝。今天可以留在屋里加固房屋。'},
  storage:{title:'室内储备',day:'箱子里是末日前留下的食物。数量有限，整理一份就少一份。'},
  bed:{title:'床铺',first:'床单有些潮湿。门窗都确认过、食物也找到后，才敢闭上眼。',day:'屋里比第一晚暖和。熄灯入睡后，系统会结算这一夜。'},
  sofa:{title:'楼下沙发',day:'柔软的沙发终于像家，但真正的卧室在楼上。'},
  stairs:{title:'通往二楼的楼梯',day:'扶手仍有新木料的气味。二楼的灯亮着，卧室在那里。'},
  stairsDown:{title:'楼梯口',day:'楼下仍有壁炉和终端。你随时可以回去。'},
  radio:{title:'旧收音机',day:'静电里偶尔夹着一两句不完整的人声。你无法确定那是不是其他幸存者。'},
  towerDoor:{title:'钢制防护门',day:'厚重的钢门嵌进混凝土门框。门禁亮着，外面是大楼的公共走廊。'},
  returnDoor:{title:'自己的安全屋',day:'门锁认出了你。回到屋里后，走廊的脚步声会被隔在门外。'},
  dropLocker:{title:'物资投放柜',day:'柜门边缘亮着青色指示灯。今天的投放似乎已经到了。'},
  neighborDoor:{title:'邻居的门铃',day:'门牌没有名字。你可以敲门，也可以保持彼此的距离。'},
  airFilter:{title:'空气净化机',day:'滤芯槽还空着。走廊投放的滤芯可以让今晚的防护更稳固。'},
  elevator:{title:'安全电梯',day:'电梯可以通向其他楼层，但当前通行权限只覆盖这一层。'}
 };
 function toast(message){$('toast').textContent=message;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),3400);}
 function currentImage(){if(s.house===0)return s.door?'shack-v1.jpg':'shack-v2.jpg';if(s.house===1)return 'cabin-v2.jpg';if(s.house===2)return floor===2?'villa-upstairs-v1.jpg':'villa-v1.jpg';return area==='corridor'?'tower-corridor-v1.jpg':'tower-v2.jpg';}
 function roomText(){if(s.house===0)return '简陋的平房，窗外贴近的丧尸和破旧房门。';if(s.house===1)return '温暖小木屋内的床、炉火与物资架，窗外仍有丧尸。';if(s.house===2)return floor===2?'两层小洋房的二楼卧室，床、收音机、储物箱和通往楼下的扶手。':'两层小洋房一层客厅，楼梯、壁炉、沙发与加固窗户。';return area==='corridor'?'高楼里的公共走廊，钢门、物资投放柜与邻居门铃。':'高层安全屋，厚钢门、空气净化机、折叠床与储备柜。';}
 function syncRoom(){stage.dataset.house=String(s.house);stage.dataset.floor=String(floor);stage.dataset.area=area;room.src='assets/'+currentImage();room.alt=roomText();stage.style.setProperty('--room-image','url("assets/'+currentImage()+'")');$('windowBarricade').hidden=!(s.house===0&&s.window);sounds.setFire(s.house===1||s.house===2);inspector.setView(s.house,floor,s.night,area);sounds.setContext?.(s.house,area);resize();renderMarks();}
 function objective(){if(Shelter.canRelocate(s))return '五夜已生还 · 可以留在这里，或接受高楼安置';if(s.phase==='end')return '这一段求生已结束 · 可以回看自己的房间';if(s.night===1)return !s.door?'先检查木门，把木板卡进门框。':!s.window?'门稳住了。接着检查窗户，遮住灯光。':!s.supplies?'搜查旧桌抽屉，取走口粮。':'准备好了。走到床边，熄灯入睡。';return '剩余准备 '+s.actionsLeft+' / 2 · '+(s.food<1?'没有食物：检查储备柜或领取应急口粮。':!s.action?'先检查门窗，决定把时间用在哪里。':s.actionsLeft===0?(s.house===2&&floor===1?'准备已用完，上楼入睡。':'准备已用完，回床入睡。'):s.house===2&&floor===1?'准备好后，上楼入睡。':'可以继续准备，也可以回床入睡。');}
 function renderMarks(){
  let layer=$('roomTraces');if(!layer){layer=document.createElement('div');layer.id='roomTraces';layer.setAttribute('aria-hidden','true');stage.append(layer);}layer.replaceChildren();
  for(const key of ['door','window']){const spot=inspector.getPoint(key==='door'&&s.house===3?'towerDoor':key);if(!spot)continue;const broken=s.damage[key]>0,fixed=Boolean(s.fixtures[key])&&!broken;if(!fixed&&!broken)continue;
   const el=document.createElement('i');el.className='room-trace '+(fixed?'trace-fixed':'trace-broken')+' trace-'+key;el.style.left=(spot.at[0]*100)+'%';el.style.top=(spot.at[1]*100)+'%';layer.append(el);}
  const w=stage.clientWidth,h=stage.clientHeight,iw=Math.min(w,h*1672/941),ih=iw*941/1672;Object.assign(layer.style,{width:iw+'px',height:ih+'px',left:(w-iw)/2+'px',top:(h-ih)/2+'px'});
 }
 function render(){const house=Shelter.houses[s.house],risk=Shelter.forecast(s);stage.dataset.alert=s.night===1||risk>=22||s.integrity<50?'high':risk>=8?'medium':'low';$('houseName').textContent=house.name+(s.house===2?(floor===2?' · 二楼卧室':' · 一楼客厅'):s.house===3?(area==='corridor'?' · 公共走廊':' · 私人居室'):'');$('dayLabel').textContent=(s.phase==='night'?'NIGHT ':'DAY ')+String(s.night+(s.phase==='end'&&s.integrity>0?1:0)).padStart(2,'0');$('coins').textContent=s.coins;$('food').textContent=s.food;$('integrity').textContent=s.integrity;
 $('chapter').textContent=s.phase==='end'&&s.integrity===0?'SHELTER LOST / 防线崩溃':s.phase==='end'?'CHAPTER COMPLETE / 清晨来信':s.night===1?'FIRST NIGHT / 首夜检查':s.house===3?'TOWER LOG / 高楼阶段':'SHELTER LOG / 第 '+s.night+' 天';$('eventTitle').textContent=Shelter.canRelocate(s)?'大楼向你开放。':s.phase==='end'?(s.integrity===0?'庇护所失守。':'钢门后的新生活。'):s.night===1?'从门和窗开始。':s.house===3?'走廊里有一份投放。':s.night===2?'醒来后，让这里好一点。':'今天，你要如何活下去？';$('narrative').textContent=s.log;$('objective').textContent=objective();$('chapterFooter').textContent=s.phase==='end'&&s.integrity===0?'安全屋失守':s.phase==='end'&&!Shelter.canRelocate(s)?'第一章 · 已完成':s.night>5?'高楼续章 · 第六天':'第一章 · 五夜生存';$('roomNote').textContent=s.night===1?'点击发光点位 · 第一视角检视':s.house===2&&floor===2?'二楼卧室 · 下楼可使用终端与壁炉':s.house===3?(area==='corridor'?'公共走廊 · 物资柜与邻居门铃':'高楼安全屋 · 钢门与净化设备'):house.name+' · 每次安睡获得 '+house.income+' 金币';$('forecast').textContent=s.phase==='end'?'已度过 '+s.survived+' 夜 · '+house.name+' · 剩余食物 '+s.food+' 份':s.night===1?'首夜无基础损耗；未挡住的撞击仍会损伤房屋。入睡消耗 1 份食物。':'守住全部撞击时损耗 '+Shelter.forecast(s)+'% · 食物 '+s.food+' 份 · 屋内储备 '+s.reserve+' 份'+(s.house===3?' · 滤芯 '+s.filters+' 枚 · 投放'+(s.dropDay===s.night?'已领取':'待领取'):'')+' · 预计收入 '+(house.income+(s.dream==='lamp'?12:0))+' 金币';
 $('actions').replaceChildren();const p=document.createElement('p');p.className='action-hint';p.textContent=Shelter.canRelocate(s)?'第五夜后的迁入由系统安置，无需补交金币。你也可以留在当前房屋检视。':s.phase==='end'?'可以继续检视房间，也可以重新开始。':'点击画面中的点位，放大物品并完成操作。';$('actions').append(p);if(Shelter.canRelocate(s)){const b=document.createElement('button');b.className='action accent';b.type='button';b.textContent='进入大楼 →';const small=document.createElement('small');small.textContent='领取高楼迁入资格，继续探索钢门后的房间与公共走廊。';b.append(small);b.addEventListener('click',()=>run('relocate'));$('actions').append(b);}$('threatText').textContent=s.phase==='end'?'你的选择已记入生存记录':Shelter.threat(s).title+(s.house===3?' · 检查净化设备与钢门':' · 点击门窗寻找线索');renderMarks();renderEnding();persist();}
 function renderEnding(){const show=s.phase==='end'&&!endingDismissed;$('ending').hidden=!show;stage.classList.toggle('ending-mode',show);if(!show)return;inspector.hide();const survived=s.integrity>0;$('endingCode').textContent=survived?'CHAPTER COMPLETE / 第 '+(s.survived+1)+' 天清晨':'SHELTER LOST / 安全屋失守';$('endingTitle').textContent=survived?(s.house===3?'钢门守住了。':'你把这里守成了家。'):'门被撞开了。';$('endingCopy').textContent=survived?'你从一间漏风的平房走到了这里。城市仍然失守，但这一夜，你有食物、有光，也有一扇能够关上的门。':'你带着背包撤出了失守的房屋。还有机会从第一夜重新布置防线。';$('endingCopy').textContent=survived?'你守住了 '+s.stats.held+' 次撞击，完成 '+s.stats.repairs+' 次加固与维护，收集 '+s.stats.foodFound+' 份食物。'+(s.house<3?'你可以留在自己选中的家，也可以接受高楼安置。':s.neighborMet?'你与邻居交换了消息，也保留了自己的空间。':'你没有敲响邻居的门，仍然独自守住了这一夜。'):'这一回有 '+s.stats.missed+' 次撞击穿过了防线。下次观察门窗的线索，把准备机会用在将要受袭的位置。';$('endingBefore').src='assets/shack-v2.jpg';$('endingAfter').src='assets/'+currentImage();$('endingRelocate').hidden=!Shelter.canRelocate(s);$('endingNights').textContent=s.survived;$('endingHouse').textContent=Shelter.houses[s.house].name;$('endingIntegrity').textContent=s.integrity;$('endingLook').textContent=survived?'留在房间看看':'查看失守的房间';}
 function finishFlash(){clearTimeout(flashTimer);$('intro').classList.add('flash-finished','finished');$('skip').hidden=true;$('enter').innerHTML='接管安全屋 <span>→</span>';}
 async function startOpening(){if(opening)return;opening=true;sounds.setFire(false);sounds.start();$('enter').innerHTML='接管安全屋 · 跳过闪回 <span>→</span>';$('skip').textContent='立即进入';await flashReady;if(entered)return;$('intro').classList.add('play-flash');flashTimer=setTimeout(finishFlash,8000);}
 function enterGame(){if(entered)return;if(!opening)startOpening();entered=true;finishFlash();$('intro').hidden=true;document.documentElement.classList.add('game-playing');document.body.classList.add('playing');window.scrollTo(0,0);$('hud').hidden=false;$('console').hidden=false;$('roomNote').hidden=false;inspector.show();syncRoom();render();startMotion();}
 function assaultBeats(){
  if(s.house===3)return [{id:'airFilter',key:'power',title:'楼层突然停电。',label:'接通备用回路',hint:'警报响起。按住接点，恢复门禁供电。'},{id:'towerDoor',key:'door',title:'黑暗里传来钢门撞击。',label:'锁住钢门',hint:'电源恢复了，门外的东西还没有走。'}];
  if(s.night===1)return [{id:'door',key:'door',title:'木门猛地一震。',label:'抵住木门',hint:'持续按住，直到撞击停止。松手会失去进度。'},{id:'window',key:'window',title:'一只手拍上玻璃。',label:'压住窗框',hint:'继续按住窗栓，不要让它弹开。'}];
  const key=Shelter.threat(s).key;return [{id:s.house===2&&floor===2&&key==='door'?'stairsDown':key,key,title:key==='door'?'楼下的门被连续撞响。':'窗外的人影追着光贴近。',label:key==='door'?'守住楼梯防线':'压住窗栓',hint:key==='door'?'楼下的加固决定了你能争取多少时间。':'窗帘正在抖动，手不能离开窗栓。'}];
 }
 function placeAssaultButton(id){const spot=inspector.getPoint(id);if(!spot)return;const w=stage.clientWidth,h=stage.clientHeight,ratio=1672/941,iw=Math.min(w,h*ratio),ih=iw/ratio;const x=(w-iw)/2+spot.at[0]*iw,y=(h-ih)/2+spot.at[1]*ih;const half=Math.max(75,$('assaultBrace').offsetWidth/2)+20;$('assaultBrace').style.left=Math.max(half,Math.min(w-half,x))+'px';$('assaultBrace').style.top=Math.max(170,Math.min(h-155,y))+'px';}
 function showAssaultBeat(){if(!assaultState)return;const beat=assaultState.beats[assaultState.index],protectedSpot=Shelter.protection(s,beat.key);$('assaultCount').textContent=(assaultState.index+1)+' / '+assaultState.beats.length;$('assaultTitle').textContent=beat.title;$('assaultBrace').firstChild.textContent=beat.label+' ';$('assaultBrace').querySelector('small').textContent=assisted?'点击完成抵挡':'持续按住 · 鼠标 / 触屏 / 空格';$('assaultHint').textContent=(protectedSpot?'先前的加固正在起作用。':'此处没有额外加固。')+(assisted?'辅助模式：点击防线即可守住，没有时间限制。':beat.hint);placeAssaultButton(beat.id);stage.classList.toggle('power-cut',beat.key==='power');stage.classList.remove('assault-hit');void stage.offsetWidth;stage.classList.add('assault-hit');sounds.impact();holdCleanup?.();cancelAnimationFrame(assaultFrame);$('assaultBrace').style.setProperty('--hold','0%');
  holdCleanup=bindShelterHold($('assaultBrace'),{duration:protectedSpot?1400:2300,assisted:()=>assisted,onProgress:p=>$('assaultBrace').style.setProperty('--hold',p*100+'%'),onComplete:()=>resolveAssaultBeat(true)});
  let remaining=protectedSpot?9500:7500,previous=0;const total=remaining;$('assaultTimer').style.transition='none';
  function timer(now){if(!assaultState||assaultState.resolving)return;const dt=previous?Math.min(60,now-previous):0;previous=now;if(!document.hidden&&!assisted&&motion)remaining-=dt;$('assaultTimer').style.width=remaining/total*100+'%';if(remaining<=0){resolveAssaultBeat(false);return;}assaultFrame=requestAnimationFrame(timer);}assaultFrame=requestAnimationFrame(timer);$('assaultBrace').focus({preventScroll:true});
 }
 function beginAssault(){busy=true;closeDetail(true);inspector.hide();window.scrollTo(0,0);stage.scrollTop=0;assaultState={beats:assaultBeats(),index:0,breaches:0,missed:[],resolving:false};$('assault').hidden=false;stage.classList.add('assault-mode');sounds.setThreat(true);showAssaultBeat();}
 function resolveAssaultBeat(held){if(!assaultState||assaultState.resolving)return;assaultState.resolving=true;holdCleanup?.();holdCleanup=null;cancelAnimationFrame(assaultFrame);clearTimeout(assaultTimeout);$('assaultTimer').style.transition='none';$('assaultTimer').style.width=held?'100%':'0%';if(!held){assaultState.breaches++;assaultState.missed.push(assaultState.beats[assaultState.index].key);}$('assaultHint').textContent=held?'防线稳住了。':'撞击撕开一道缝，房屋将额外受损。';stage.classList.toggle('assault-missed',!held);sounds.impact();setTimeout(()=>{if(!assaultState)return;stage.classList.remove('assault-missed');assaultState.index++;assaultState.resolving=false;if(assaultState.index<assaultState.beats.length)showAssaultBeat();else finishAssault();},motion?480:90);}
 async function finishAssault(){if(!assaultState)return;const breaches=assaultState.breaches,missed=assaultState.missed,beats=assaultState.beats.length;assaultState=null;holdCleanup?.();cancelAnimationFrame(assaultFrame);stage.classList.remove('power-cut');clearTimeout(assaultTimeout);$('assault').hidden=true;stage.classList.remove('assault-mode','assault-hit','assault-missed');sounds.setThreat(false);const result=Shelter.act(s,'sleep',{breaches,missed,beats});if(!result.ok){inspector.show();busy=false;return;}stage.classList.add('lights-out');$('nightVeil').classList.add('active');await wait(motion?1300:120);s=result.state;endingDismissed=false;syncRoom();render();await wait(motion?450:60);stage.classList.remove('lights-out');$('nightVeil').classList.remove('active');if($('ending').hidden)inspector.show();busy=false;if(!$('ending').hidden)$('endingLook').focus({preventScroll:true});}
 function zoomImage(img,x,y,scale=2.3){const left=Math.max(1-scale,Math.min(0,.5-scale*x)),top=Math.max(1-scale,Math.min(0,.5-scale*y));Object.assign(img.style,{width:scale*100+'%',height:scale*100+'%',left:left*100+'%',top:top*100+'%'});}
 function inspect(item){if(!entered||busy)return;activeSpot=item;const key=item.id==='airFilter'?'power':['door','towerDoor','stairsDown'].includes(item.id)?'door':item.id==='window'?'window':null;if(key){const observed=Shelter.act(s,'observe',{key});if(observed.ok){s=observed.state;render();}}sounds.setContext?.(s.house,area,item.id);const detail=$('detail'),frame=$('detailFrame');frame.className='detail-frame';$('lockerItems').textContent='';$('detailImage').src=room.src;$('detailAfter').src=room.src;zoomImage($('detailImage'),...item.at);zoomImage($('detailAfter'),...item.at);$('terminalProjection').hidden=item.id!=='terminal';detail.hidden=false;renderDetail();$('detailClose').focus({preventScroll:true});}
 function closeDetail(force=false){if($('detail').hidden||busy&&!force)return;handsCleanup?.();handsCleanup=null;sounds.setContext?.(s.house,area);$('detail').hidden=true;$('detailFrame').className='detail-frame';$('lockerItems').textContent='';const last=activeSpot;activeSpot=null;if(last){const b=$('hotspots').querySelector('[data-spot="'+last.id+'"]');b?.focus({preventScroll:true});}}
 function modalButton(label,detail,action,disabled=false,primary=false){const b=document.createElement('button');b.className=primary?'modal-action primary-action':'modal-action';b.disabled=busy||disabled;b.textContent=label;if(detail){const small=document.createElement('small');small.textContent=detail;b.append(small);}b.addEventListener('click',()=>run(action));$('detailActions').append(b);}
 function renderDetail(){if(!activeSpot||$('detail').hidden)return;const id=activeSpot.id,item=data[id],first=s.night===1;$('detailEyebrow').textContent=(s.house===3?(area==='corridor'?'TOWER CORRIDOR / ':'TOWER ROOM / '):s.house===2&&floor===2?'SECOND FLOOR / ':'FIRST PERSON / ')+'检视';$('detailTitle').textContent=s.house===3&&id==='bed'?'折叠床':s.house===3&&id==='window'?'高层防护窗':s.house===3&&id==='storage'?'封闭物资柜':item.title;$('detailText').textContent=s.house===3&&id==='bed'?'折叠床靠着暖灯。至少完成一次准备、留好一份食物，就可以入睡。':s.house===3&&id==='window'?'加固玻璃将街道和丧尸压成很远的影子。密封条仍需要定期检查。':s.house===3&&id==='storage'?'柜中物资摆放整齐。室内储备有限，走廊投放柜每天会额外提供一份。':first&&item.first?item.first:item.day||item.first;$('detailCode').textContent='OBJECT / '+id.toUpperCase();$('detailCoordinate').textContent=Shelter.houses[s.house].name+(s.house===2?' · '+(floor===2?'二楼卧室':'一楼客厅'):s.house===3?' · '+(area==='corridor'?'公共走廊':'私人居室'):'');$('terminalHouse').textContent=Shelter.houses[s.house].name;$('terminalCoins').textContent=s.coins;$('terminalReserve').textContent=s.reserve;$('detailActions').replaceChildren();if(s.phase==='end'){if(Shelter.canRelocate(s)&&id==='terminal')modalButton('领取资格，进入大楼','第五夜后开放，无需补交金币。','relocate',false,true);if(id==='towerDoor')modalButton('进入公共走廊','回看物资投放柜和邻居的门。','corridor',false,true);if(id==='returnDoor')modalButton('回到自己的房间','关上钢门。','towerRoom',false,true);modalButton('重新开始第一章','从末日警报重新体验。','restart',false,!Shelter.canRelocate(s)&&id!=='towerDoor'&&id!=='returnDoor');return;}
 if(first){if(id==='door')modalButton(s.door?'木板已经卡牢':'把木板抵进门框',s.door?'门已加固。':'木板会滑入卡槽，挡住外面的撞击。','door',s.door,true);if(id==='window')modalButton(s.window?'窗框已加固':'扣紧窗栓并加固窗框',s.window?'窗户暂时安全。':'装上金属横挡，扣紧窗栓。','window',s.window,true);if(id==='supplies')modalButton(s.supplies?'抽屉已搜过':'拉开抽屉搜查',s.supplies?'已拿到一份食物。':'找出可以过夜的食物。','supplies',s.supplies,true);if(id==='bed')modalButton('熄灯，度过第一夜',s.door&&s.window&&s.supplies?'夜间操作：长按门窗。也可以在右上角开启辅助模式。':'还需要加固门窗并找到食物。','sleep',!s.door||!s.window||!s.supplies,true);return;}
 if(id==='door'||id==='towerDoor')modalButton(s.house===3?'维护钢门锁扣':'加固门框支撑','完整度 +10；撞门时更容易抵挡。消耗一次准备。','braceDoor',!Shelter.canPrepare(s,'door'),true);if(id==='door')modalButton('出门','查看外部世界。','outside');
 if(id==='window')modalButton(s.house===3?'检查防护窗密封条':'再加固窗框','遮住光线、锁紧窗栓。完整度 +10；消耗一次准备。','sealWindow',!Shelter.canPrepare(s,'window'),true);
 if(id==='terminal'){if(s.house<3){const next=Shelter.houses[s.house+1],gate=next.minNight&&s.night<next.minNight?'第 '+next.minNight+' 天开放 · ':'';modalButton('升级为'+next.name,gate+next.cost+' 金币 · 完整度恢复，获得一份食物。','upgrade',!Shelter.canUpgrade(s),true);}if(!s.dream){modalButton('梦境：一盏暖灯','今晚金币 +12。','lamp');modalButton('梦境：紧闭的门','今晚基础损耗减少 8，不消耗准备机会。','shield');}}
 if(id==='storage')modalButton('整理一份室内储备','食物 +1 · 库存 '+s.reserve+' · 消耗一次准备。','sort',!Shelter.canPrepare(s,'food')||s.reserve<1,true);
 if(id==='fire'||id==='workbench')modalButton('加固安全屋','完整度 +20，基础损耗减少 6；消耗一次准备。','prepare',!Shelter.canPrepare(s,'structure'),true);
 if(id==='bed')modalButton('关灯入睡',!s.action?'至少完成一次准备；梦境为可选加成。':s.food<1?'食物不足，先检查储备柜。':'消耗 1 份食物；夜间需要持续守住防线。','sleep',!Shelter.canSleep(s),true);
 if(id==='stairs'||id==='sofa')modalButton('上楼看看','进入二楼卧室。','upstairs',false,true);
 if(id==='stairsDown')modalButton('回到一楼','返回客厅、壁炉与安居终端。','downstairs',false,true);
 if(id==='radio')modalButton('调整频率','收听城外残存的信号。','radio',false,true);
 if(id==='towerDoor')modalButton('进入公共走廊','去投放柜领取物资；邻居交流由你决定。','corridor',false,true);
 if(id==='returnDoor')modalButton('回到自己的房间','关上钢门，继续今天的安排。','towerRoom',false,true);
 if(id==='dropLocker')modalButton(s.dropDay===s.night?'今天的投放已领取':'打开物资投放柜',s.dropDay===s.night?'明天指示灯会再次亮起。':'食物 +1、滤芯 +1；不消耗今日行动。','claimDrop',s.dropDay===s.night,true);
 if(id==='neighborDoor'){modalButton(s.neighborMet?'你已经和邻居打过招呼':'按响邻居门铃',s.neighborMet?'可以继续保持距离。':'只听一句话，不会扣除资源。','contactNeighbor',s.neighborMet,true);modalButton('保持距离','今天不接触其他住户。','skipNeighbor');}
 if(id==='airFilter')modalButton('安装一枚新滤芯','滤芯 '+s.filters+' 枚 · 修复备用回路，抵御停电；消耗一次准备。','installFilter',!Shelter.canPrepare(s,'power')||s.filters<1,true);
 if(['storage','bed','terminal'].includes(id)&&s.food===0)modalButton('领取应急口粮',s.coins>=12?'花费 12 金币，不消耗准备机会。':'拆开墙内应急箱，损失 10 点完整度。','emergency',s.emergencyDay===s.night);
 if(['door','window','towerDoor','airFilter','stairsDown','radio'].includes(id))$('detailText').textContent=Shelter.threat(s).clue+' '+(Shelter.protection(s,Shelter.threat(s).key)?'对应防线已准备。':'对应防线尚未准备。');
 if(id==='elevator')modalButton('其他楼层尚未开放','这一章只探索自己的楼层。','none',true);
 }
 async function run(action,completed=false){if(busy||handsCleanup&&!completed)return;const kinds={door:'door',braceDoor:'door',window:'window',sealWindow:'window',supplies:'drawer',sort:'drawer',claimDrop:'locker',installFilter:'power'};if(kinds[action]&&!completed&&Shelter.act(s,action).ok){$('detailActions').replaceChildren();handsCleanup=createShelterHands({frame:$('detailFrame'),kind:action==='braceDoor'&&s.house===3?'steel':kinds[action],assisted:()=>assisted,impact:()=>sounds.impact(),onComplete:()=>{handsCleanup=null;run(action,true);}});return;}if(action==='outside'){$('outsideNotice').hidden=false;$('outsideBack').focus();return;}if(action==='skipNeighbor'){closeDetail();return;}if(action==='restart'){restart();return;}if(action==='radio'){$('detailFrame').classList.add('scanning');$('detailText').textContent='沙沙声里传来一句“还有人吗？”接着，信号再次中断。';return;}if(action==='sleep'){if(Shelter.act(s,'sleep').ok)beginAssault();return;}if(['upstairs','downstairs','corridor','towerRoom'].includes(action)){busy=true;closeDetail(true);inspector.hide();const target=action==='upstairs'?'villa-upstairs-v1.jpg':action==='downstairs'?'villa-v1.jpg':action==='corridor'?'tower-corridor-v1.jpg':'tower-v2.jpg';$('nextRoom').src='assets/'+target;stage.classList.add('changing-floor');await wait(motion?620:100);if(action==='upstairs'||action==='downstairs')floor=action==='upstairs'?2:1;else area=action==='corridor'?'corridor':'room';stage.classList.remove('changing-floor');syncRoom();inspector.show();busy=false;render();return;}
 const result=Shelter.act(s,action);if(!result.ok)return;
 if(action==='upgrade'||action==='relocate'){busy=true;closeDetail(true);inspector.hide();try{await preload(Shelter.houses[result.state.house].image);$('nextRoom').src='assets/'+Shelter.houses[result.state.house].image;$('upgradeLabel').textContent=Shelter.houses[result.state.house].name+' · 建造中';stage.classList.add('upgrading');await wait(motion?2700:220);s=result.state;endingDismissed=false;floor=1;area='room';stage.classList.remove('upgrading');$('upgradeLabel').textContent='';if(s.house===1)await sounds.setMusicSource('cabin-music.m4a');if(s.house===3)await sounds.setMusicSource('tower-music.m4a');syncRoom();toast((action==='relocate'?'迁入完成 · ':'升级完成 · ')+Shelter.houses[s.house].name);}catch(e){stage.classList.remove('upgrading');toast('房间图片未载入，金币没有扣除。请重试。');}inspector.show();busy=false;render();return;}
 busy=true;const frame=$('detailFrame');if(action==='door'||action==='braceDoor'){frame.classList.add('installing');await wait(motion?1350:170);s=result.state;room.src='assets/'+currentImage();$('detailAfter').src='assets/'+currentImage();frame.classList.remove('installing');frame.classList.add('installed');}
 else if(action==='window'||action==='sealWindow'){frame.classList.add('reinforcing');await wait(motion?1100:150);s=result.state;frame.classList.remove('reinforcing');frame.classList.add('secured');$('windowBarricade').hidden=s.house!==0;}
 else if(action==='supplies'||action==='sort'){frame.classList.add('opening-drawer');await wait(motion?850:130);s=result.state;frame.classList.add('opened-drawer');}
 else if(action==='claimDrop'){frame.classList.add('opening-locker');await wait(motion?1050:150);s=result.state;$('lockerItems').textContent='食物 +1 · 滤芯 +1';frame.classList.remove('opening-locker');frame.classList.add('opened-locker');}
 else{frame.classList.add('scanning');await wait(motion?600:100);s=result.state;}
 busy=false;render();renderDetail();$('detailText').textContent=s.log;}
 $('enter').addEventListener('click',()=>{if(!opening)startOpening();else enterGame();});$('skip').addEventListener('click',enterGame);$('detailClose').addEventListener('click',()=>closeDetail());$('detail').addEventListener('click',e=>{if(e.target===$('detail'))closeDetail();});$('outsideBack').addEventListener('click',()=>{$('outsideNotice').hidden=true;$('detailClose').focus();});document.addEventListener('keydown',e=>{if(e.key==='Tab'){const modal=['outsideNotice','detail','assault','ending'].map($).find(el=>!el.hidden);if(modal){const nodes=[...modal.querySelectorAll('button:not(:disabled),input:not(:disabled),[tabindex="0"]')].filter(el=>!el.hidden&&el.getClientRects().length);const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}if(e.key==='Escape'){if(!$('outsideNotice').hidden){$('outsideNotice').hidden=true;$('detailClose').focus();}else closeDetail();}});
 $('assaultYield').addEventListener('click',()=>resolveAssaultBeat(false));
 $('endingLook').addEventListener('click',()=>{endingDismissed=true;renderEnding();inspector.show();});$('endingRestart').addEventListener('click',restart);$('endingRelocate').addEventListener('click',()=>{endingDismissed=true;renderEnding();run('relocate');});$('journal').addEventListener('click',()=>{const expanded=$('console').classList.toggle('expanded');$('journal').setAttribute('aria-expanded',String(expanded));$('journal').textContent=expanded?'收起记录':'生存记录';});$('assist').addEventListener('click',()=>{if(busy||handsCleanup){toast('完成当前操作后可以切换辅助模式。');return;}assisted=!assisted;$('assist').textContent=assisted?'辅助：开启':'辅助：关闭';$('assist').setAttribute('aria-pressed',String(assisted));toast(assisted?'辅助操作已开启：物品可以分步点击，夜间没有倒计时。':'辅助操作已关闭：拖动物品，持续按住防线。');});
 $('music').addEventListener('click',()=>{sounds.setMusic(!sounds.music);$('music').textContent=sounds.music?'音乐：开启':'音乐：关闭';$('music').setAttribute('aria-pressed',String(sounds.music));});$('audioRetry').addEventListener('click',()=>{$('audioRetry').hidden=true;sounds.retry();});$('restart').addEventListener('click',()=>{if(!busy)restart();});
 function motionUI(){document.body.classList.toggle('still',!motion);$('motion').textContent=motion?'动态：开启':'动态：关闭';$('motion').setAttribute('aria-pressed',String(motion));if(assaultState&&!assaultState.resolving){clearTimeout(assaultTimeout);showAssaultBeat();}}$('motion').addEventListener('click',()=>{motion=!motion;if(!motion&&opening)finishFlash();motionUI();startMotion();});matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',e=>{motion=!e.matches;if(!motion&&opening)finishFlash();motionUI();startMotion();});
 function resize(){const dpr=Math.min(devicePixelRatio||1,2);canvas.width=stage.clientWidth*dpr;canvas.height=stage.clientHeight*dpr;const ratio=1672/941,iw=Math.min(stage.clientWidth,stage.clientHeight*ratio),ih=iw/ratio,ox=(stage.clientWidth-iw)/2,oy=(stage.clientHeight-ih)/2;const point=s.house===0?[.643,.05]:s.house===1?[.815,.35]:s.house===3?(area==='corridor'?[.28,.15]:[.38,.35]):floor===2?[.36,.29]:[.812,.46];stage.style.setProperty('--lamp-x',((ox+point[0]*iw)/stage.clientWidth*100)+'%');stage.style.setProperty('--lamp-y',((oy+point[1]*ih)/stage.clientHeight*100)+'%');inspector.refresh();renderMarks();if(assaultState)placeAssaultButton(assaultState.beats[assaultState.index].id);}new ResizeObserver(resize).observe(stage);
 function draw(t){frame=0;if(!entered||!motion||document.hidden){ctx.clearRect(0,0,canvas.width,canvas.height);return;}frame=requestAnimationFrame(draw);if(t-last<32)return;last=t;const w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);const iw=Math.min(w,h*1672/941),ih=iw*941/1672;ctx.save();ctx.translate((w-iw)/2,(h-ih)/2);ctx.scale(iw,ih);const seconds=t/1000;
 if((s.house===1||s.house===2)&&floor===1){const p=s.house===1?{x:.283,y:.526,width:.048,height:.086}:{x:.350,y:.611,width:.047,height:.057};ctx.save();ctx.beginPath();ctx.rect(p.x,p.y-p.height,p.width,p.height);ctx.clip();ctx.globalCompositeOperation='screen';for(let i=0;i<12;i++){const x=p.x+.003+i*p.width/13,y=p.y,height=p.height*(.35+.35*(.5+.5*Math.sin(seconds*(2+i*.1)+i))),drift=.003*Math.sin(seconds*3+i);const g=ctx.createLinearGradient(0,y,0,y-height);g.addColorStop(0,'#ffb34505');g.addColorStop(.3,'#ffd47a80');g.addColorStop(1,'#ff921500');ctx.fillStyle=g;ctx.beginPath();ctx.moveTo(x-.004,y);ctx.quadraticCurveTo(x-.007,y-height*.5,x+drift,y-height);ctx.quadraticCurveTo(x+.005,y-height*.3,x+.003,y);ctx.fill();}ctx.restore();}
 if(stage.classList.contains('upgrading'))for(let i=0;i<36;i++){const x=(seconds*.16+i*.027)%1,y=.15+(i*.171%.75);ctx.fillStyle='rgba(255,218,132,'+(.3+.4*Math.sin(seconds*4+i)**2)+')';ctx.beginPath();ctx.ellipse(x,y,.0012,.002,0,0,Math.PI*2);ctx.fill();}ctx.restore();}
 function startMotion(){cancelAnimationFrame(frame);frame=0;if(entered&&motion&&!document.hidden)frame=requestAnimationFrame(draw);else ctx.clearRect(0,0,canvas.width,canvas.height);}document.addEventListener('visibilitychange',startMotion);motionUI();if(entered){$('intro').hidden=true;document.documentElement.classList.add('game-playing');document.body.classList.add('playing');window.scrollTo(0,0);$('hud').hidden=false;$('console').hidden=false;$('roomNote').hidden=false;inspector.show();syncRoom();render();startMotion();const resumeSound=()=>{sounds.start();document.removeEventListener('pointerdown',resumeSound);document.removeEventListener('keydown',resumeSound);};document.addEventListener('pointerdown',resumeSound,{once:true});document.addEventListener('keydown',resumeSound,{once:true});}else render();
})();
