'use strict';
(()=>{
 const $=id=>document.getElementById(id),stage=$('stage'),room=$('room'),canvas=$('embers'),ctx=canvas.getContext('2d');
 const saveKey='anju-protocol-progress-v1';
 function loadProgress(){try{const saved=JSON.parse(localStorage.getItem(saveKey));const state=saved?.state;if(!state||!Number.isInteger(state.house)||state.house<0||state.house>=Shelter.houses.length||!Number.isInteger(state.night)||state.night<1||state.night>6||!['night','day','end'].includes(state.phase)||!Number.isFinite(state.coins)||!Number.isFinite(state.food))return null;return saved;}catch{return null;}}
 const saved=loadProgress();
 let s=saved?.state||Shelter.create(),floor=saved?.floor===2&&saved.state.house===2?2:1,area=saved?.area==='corridor'&&saved.state.house===3?'corridor':'room',entered=Boolean(saved),opening=false,busy=false,activeSpot=null,motion=!matchMedia('(prefers-reduced-motion: reduce)').matches,frame=0,last=0,flashTimer=0,toastTimer=0,assaultState=null,assaultTimeout=0,endingDismissed=false;
 const musicFile=s.house===3?'tower-music.m4a':s.house>0?'cabin-music.m4a':'first-night.m4a';
 const sounds=createShelterAudio({musicFile,musicDefault:true,onError:()=>{$('audioRetry').hidden=false;toast('点击“恢复环境音”继续播放。');}});
 function persist(){if(!entered)return;try{localStorage.setItem(saveKey,JSON.stringify({state:s,floor,area}));}catch{}}
 function restart(){try{localStorage.removeItem(saveKey);}catch{}location.reload();}
 const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));const preloads=new Map();
 function preload(file){if(!preloads.has(file)){const image=new Image();preloads.set(file,new Promise((resolve,reject)=>{image.onload=()=>resolve(image);image.onerror=()=>{preloads.delete(file);reject(new Error('图片未载入'));};image.src='assets/'+file;}));}return preloads.get(file);}
 const flashReady=Promise.allSettled(['bridge-v1.jpg','street-v1.jpg'].map(preload));['cabin-v2.jpg','villa-v1.jpg','villa-upstairs-v1.jpg','shack-v1.jpg','tower-v2.jpg','tower-corridor-v1.jpg'].forEach(f=>preload(f).catch(()=>{}));
 const inspector=createRoomInspector({stage,layer:$('exploreLayer'),hotspots:$('hotspots'),onInspect:inspect});
 const data={
  door:{title:'木门',first:'木门还没有固定。那块旧木板靠在墙边，窗外的脚步正在靠近。',day:'门外通向失守的街道。门锁完好，你听见路口传来断续的嘶吼。'},
  window:{title:'窗户',first:'玻璃外有血掌印。窗栓松动，丧尸的脸几乎贴上了玻璃。',day:'站在加固窗前，你能看到屋外的动静。今晚的威胁已记录在系统中。'},
  supplies:{title:'旧桌抽屉',first:'抽屉里似乎卡着一个扁扁的纸包。'},
  terminal:{title:'安居终端',day:'透明系统页在桌面亮起。金币、梦境回收与房屋升级都汇集在这里。'},
  workbench:{title:'加固工具',day:'木板、铁钉和一卷胶带。你可以用今天的时间加固安全屋。'},
  fire:{title:'壁炉',day:'火光照亮了门窗接缝。今天可以留在屋里加固房屋。'},
  storage:{title:'室内储备',day:'箱子里是末日前留下的食物。数量有限，整理一份就少一份。'},
  bed:{title:'床铺',first:'床单有些潮湿。门窗都确认过、食物也找到后，才敢闭上眼。',day:'屋里比第一晚暖和。熄灯入睡后，系统会结算这一夜。'},
  sofa:{title:'楼下沙发',day:'柔软的沙发终于像家，但真正的卧室在楼上。'},
  stairs:{title:'通往二楼的楼梯',day:'扶手仍有新木料的气味。二楼的灯亮着，卧室在那里。'},
  stairsDown:{title:'楼梯口',day:'楼下仍有壁炉和终端。你随时可以回去。'},
  radio:{title:'旧收音机',day:'静电里偶尔夹着一两句不完整的人声。你无法确定那是不是其他幸存者。'},
  towerDoor:{title:'钢制防护门',day:'厚重的钢门嵌进混凝土门框。门禁亮着，外面是大楼的公共走廊。'},
  returnDoor:{title:'自己的安全屋',day:'门锁认出了你。回到屋里后，走廊的脚步声会被隔在门外。'},
  dropLocker:{title:'物资投放柜',day:'柜门边缘亮着青色指示灯。今天的投放似乎已经到了。'},
  neighborDoor:{title:'邻居的门铃',day:'门牌没有名字。你可以敲门，也可以保持彼此的距离。'},
  airFilter:{title:'空气净化机',day:'滤芯槽还空着。走廊投放的滤芯可以让今晚的防护更稳固。'},
  elevator:{title:'安全电梯',day:'电梯可以通向其他楼层，但当前通行权限只覆盖这一层。'}
 };
 function toast(message){$('toast').textContent=message;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),3400);}
 function currentImage(){if(s.house===0)return s.door?'shack-v1.jpg':'shack-v2.jpg';if(s.house===1)return 'cabin-v2.jpg';if(s.house===2)return floor===2?'villa-upstairs-v1.jpg':'villa-v1.jpg';return area==='corridor'?'tower-corridor-v1.jpg':'tower-v2.jpg';}
 function roomText(){if(s.house===0)return '简陋的平房，窗外贴近的丧尸和破旧房门。';if(s.house===1)return '温暖小木屋内的床、炉火与物资架，窗外仍有丧尸。';if(s.house===2)return floor===2?'两层小洋房的二楼卧室，床、收音机、储物箱和通往楼下的扶手。':'两层小洋房一层客厅，楼梯、壁炉、沙发与加固窗户。';return area==='corridor'?'高楼里的公共走廊，钢门、物资投放柜与邻居门铃。':'高层安全屋，厚钢门、空气净化机、折叠床与储备柜。';}
 function syncRoom(){stage.dataset.house=String(s.house);stage.dataset.floor=String(floor);stage.dataset.area=area;room.src='assets/'+currentImage();room.alt=roomText();stage.style.setProperty('--room-image','url("assets/'+currentImage()+'")');$('windowBarricade').hidden=!(s.house===0&&s.window);sounds.setFire(s.house===1||s.house===2);inspector.setView(s.house,floor,s.night,area);resize();}
 function objective(){if(Shelter.canRelocate(s))return '已度过五夜 · 高楼迁入资格已开放 → 点击下方按钮进入大楼';if(s.phase==='end')return s.integrity===0?'安全屋失守 · 可以重新开始': '第一章完成 · 已度过 '+s.survived+' 夜 · 可继续检视房间';if(s.night===1)return '首夜目标  '+(s.door?'✓':'○')+' 抵住木门　'+(s.window?'✓':'○')+' 加固窗户　'+(s.supplies?'✓':'○')+' 搜查旧桌　→ 熄灯入睡';if(s.house===3)return '高楼目标  '+(s.dropDay===s.night?'✓':'○')+' 领取投放　'+(s.dream?'✓':'○')+' 选择梦境　'+(s.action?'✓':'○')+' 维护设备或整理储备　→ 回屋入睡';return '今日目标  '+(s.dream?'✓':'○')+' 选择梦境　'+(s.action?'✓':'○')+' 整理储备或加固　→ '+(s.house===2&&floor===1?'上楼睡觉':'回床入睡');}
 function render(){const house=Shelter.houses[s.house],risk=Shelter.forecast(s);stage.dataset.alert=s.night===1||risk>=22||s.integrity<50?'high':risk>=8?'medium':'low';$('houseName').textContent=house.name+(s.house===2?(floor===2?' · 二楼卧室':' · 一楼客厅'):s.house===3?(area==='corridor'?' · 公共走廊':' · 私人居室'):'');$('dayLabel').textContent=(s.phase==='night'?'NIGHT ':'DAY ')+String(s.night+(s.phase==='end'&&s.integrity>0?1:0)).padStart(2,'0');$('coins').textContent=s.coins;$('food').textContent=s.food;$('integrity').textContent=s.integrity;
 $('chapter').textContent=s.phase==='end'&&s.integrity===0?'SHELTER LOST / 防线崩溃':s.phase==='end'?'CHAPTER COMPLETE / 清晨来信':s.night===1?'FIRST NIGHT / 首夜检查':s.house===3?'TOWER LOG / 高楼阶段':'SHELTER LOG / 第 '+s.night+' 天';$('eventTitle').textContent=Shelter.canRelocate(s)?'大楼向你开放。':s.phase==='end'?(s.integrity===0?'庇护所失守。':'钢门后的新生活。'):s.night===1?'从门和窗开始。':s.house===3?'走廊里有一份投放。':s.night===2?'醒来后，让这里好一点。':'今天，你要如何活下去？';$('narrative').textContent=s.log;$('objective').textContent=objective();$('chapterFooter').textContent=s.phase==='end'&&s.integrity===0?'安全屋失守':s.phase==='end'&&!Shelter.canRelocate(s)?'第一章 · 已完成':s.night>5?'高楼续章 · 第六天':'第一章 · 五夜生存';$('roomNote').textContent=s.night===1?'点击发光点位 · 第一视角检视':s.house===2&&floor===2?'二楼卧室 · 下楼可使用终端与壁炉':s.house===3?(area==='corridor'?'公共走廊 · 物资柜与邻居门铃':'高楼安全屋 · 钢门与净化设备'):house.name+' · 每次安睡获得 '+house.income+' 金币';$('forecast').textContent=s.phase==='end'?'已度过 '+s.survived+' 夜 · '+house.name+' · 剩余食物 '+s.food+' 份':s.night===1?'首夜保护：房屋不会受损。入睡消耗 1 份食物，获得 20 金币。':'今晚预计损耗 '+Shelter.forecast(s)+'% · 食物 '+s.food+' 份 · 屋内储备 '+s.reserve+' 份'+(s.house===3?' · 滤芯 '+s.filters+' 枚 · 投放'+(s.dropDay===s.night?'已领取':'待领取'):'')+' · 预计收入 '+(house.income+(s.dream==='lamp'?12:0))+' 金币';
 $('actions').replaceChildren();const p=document.createElement('p');p.className='action-hint';p.textContent=Shelter.canRelocate(s)?'第五夜后的迁入由系统安置，无需补交金币。你也可以留在当前房屋检视。':s.phase==='end'?'可以继续检视房间，也可以重新开始。':'点击画面中的点位，放大物品并完成操作。';$('actions').append(p);if(Shelter.canRelocate(s)){const b=document.createElement('button');b.className='action accent';b.type='button';b.textContent='进入大楼 →';const small=document.createElement('small');small.textContent='领取高楼迁入资格，继续探索钢门后的房间与公共走廊。';b.append(small);b.addEventListener('click',()=>run('relocate'));$('actions').append(b);}renderEnding();persist();}
 function renderEnding(){const show=s.phase==='end'&&!Shelter.canRelocate(s)&&!endingDismissed;$('ending').hidden=!show;stage.classList.toggle('ending-mode',show);if(!show)return;inspector.hide();const survived=s.integrity>0;$('endingCode').textContent=survived?'CHAPTER COMPLETE / 第 '+(s.survived+1)+' 天清晨':'SHELTER LOST / 安全屋失守';$('endingTitle').textContent=survived?'钢门守住了。':'门被撞开了。';$('endingCopy').textContent=survived?'你从一间漏风的平房走到了这里。城市仍然失守，但这一夜，你有食物、有光，也有一扇能够关上的门。':'你带着背包撤出了失守的房屋。还有机会从第一夜重新布置防线。';$('endingNights').textContent=s.survived;$('endingHouse').textContent=Shelter.houses[s.house].name;$('endingIntegrity').textContent=s.integrity;$('endingLook').textContent=survived?'留在房间看看':'查看失守的房间';}
 function finishFlash(){clearTimeout(flashTimer);$('intro').classList.add('flash-finished','finished');$('skip').hidden=true;$('enter').innerHTML='接管安全屋 <span>→</span>';}
 async function startOpening(){if(opening)return;opening=true;sounds.setFire(false);sounds.start();$('enter').innerHTML='接管安全屋 · 跳过闪回 <span>→</span>';$('skip').textContent='立即进入';await flashReady;if(entered)return;$('intro').classList.add('play-flash');flashTimer=setTimeout(finishFlash,8000);}
 function enterGame(){if(entered)return;if(!opening)startOpening();entered=true;finishFlash();$('intro').hidden=true;document.documentElement.classList.add('game-playing');document.body.classList.add('playing');window.scrollTo(0,0);$('hud').hidden=false;$('console').hidden=false;$('roomNote').hidden=false;inspector.show();syncRoom();render();startMotion();}
 function assaultBeats(){if(s.house===3)return [{id:'towerDoor',title:'走廊里响起重击。',label:'锁紧钢门',hint:'隔壁的脚步突然乱了。稳住门锁。'},{id:'airFilter',title:'通风阀正在震动。',label:'压住阀门',hint:'切断外部进气，等待警报消失。'}];if(s.house===2&&floor===2)return [{id:s.night%2?'window':'stairsDown',title:s.night%2?'二楼窗户被拍响。':'楼下传来撞门声。',label:s.night%2?'压紧窗栓':'守住楼梯口',hint:'它们还没有进来。'}];return s.night===1?[{id:'door',title:'木门猛地一震。',label:'抵住木门',hint:'第一夜，木板正在门框里颤动。'},{id:'window',title:'一只手拍上玻璃。',label:'压紧窗框',hint:'血掌印在玻璃上缓缓滑动。'}]:[{id:s.night%2?'window':'door',title:s.night%2?'窗外有人影贴近。':'门板传来急促的撞击。',label:s.night%2?'压紧窗框':'抵住门框',hint:'如果松手，安全屋会额外受损。'}];}
 function placeAssaultButton(id){const spot=inspector.getPoint(id);if(!spot)return;const w=stage.clientWidth,h=stage.clientHeight,ratio=1672/941,iw=Math.min(w,h*ratio),ih=iw/ratio;const x=(w-iw)/2+spot.at[0]*iw,y=(h-ih)/2+spot.at[1]*ih;$('assaultBrace').style.left=x+'px';$('assaultBrace').style.top=y+'px';}
 function showAssaultBeat(){if(!assaultState)return;const beat=assaultState.beats[assaultState.index];$('assaultCount').textContent=String(assaultState.index+1).padStart(2,'0')+' / '+String(assaultState.beats.length).padStart(2,'0');$('assaultTitle').textContent=beat.title;$('assaultBrace').firstChild.textContent=beat.label+' ';$('assaultHint').textContent=beat.hint;placeAssaultButton(beat.id);stage.classList.remove('assault-hit');void stage.offsetWidth;stage.classList.add('assault-hit');sounds.impact();clearTimeout(assaultTimeout);$('assaultTimer').style.transition='none';$('assaultTimer').style.width='100%';if(motion&&!document.hidden){requestAnimationFrame(()=>{if(!assaultState)return;$('assaultTimer').style.transition='width 4.5s linear';$('assaultTimer').style.width='0%';});assaultTimeout=setTimeout(()=>resolveAssaultBeat(false),4500);}$('assaultBrace').focus({preventScroll:true});}
 function beginAssault(){busy=true;closeDetail(true);inspector.hide();window.scrollTo(0,0);stage.scrollTop=0;assaultState={beats:assaultBeats(),index:0,breaches:0,resolving:false};$('assault').hidden=false;stage.classList.add('assault-mode');sounds.setThreat(true);showAssaultBeat();}
 function resolveAssaultBeat(held){if(!assaultState||assaultState.resolving)return;assaultState.resolving=true;clearTimeout(assaultTimeout);$('assaultTimer').style.transition='none';$('assaultTimer').style.width=held?'100%':'0%';if(!held)assaultState.breaches++;$('assaultHint').textContent=held?'防线稳住了。':'撞击撕开一道缝，房屋将额外受损。';stage.classList.toggle('assault-missed',!held);sounds.impact();setTimeout(()=>{if(!assaultState)return;stage.classList.remove('assault-missed');assaultState.index++;assaultState.resolving=false;if(assaultState.index<assaultState.beats.length)showAssaultBeat();else finishAssault();},motion?480:90);}
 async function finishAssault(){if(!assaultState)return;const breaches=assaultState.breaches;assaultState=null;clearTimeout(assaultTimeout);$('assault').hidden=true;stage.classList.remove('assault-mode','assault-hit','assault-missed');sounds.setThreat(false);const result=Shelter.act(s,'sleep',{breaches});if(!result.ok){inspector.show();busy=false;return;}stage.classList.add('lights-out');$('nightVeil').classList.add('active');await wait(motion?1300:120);s=result.state;syncRoom();render();await wait(motion?450:60);stage.classList.remove('lights-out');$('nightVeil').classList.remove('active');if($('ending').hidden)inspector.show();busy=false;if(!$('ending').hidden)$('endingLook').focus({preventScroll:true});}
 function zoomImage(img,x,y,scale=2.3){const left=Math.max(1-scale,Math.min(0,.5-scale*x)),top=Math.max(1-scale,Math.min(0,.5-scale*y));Object.assign(img.style,{width:scale*100+'%',height:scale*100+'%',left:left*100+'%',top:top*100+'%'});}
 function inspect(item){if(!entered||busy)return;activeSpot=item;const detail=$('detail'),frame=$('detailFrame');frame.className='detail-frame';$('lockerItems').textContent='';$('detailImage').src=room.src;$('detailAfter').src=room.src;zoomImage($('detailImage'),...item.at);zoomImage($('detailAfter'),...item.at);$('terminalProjection').hidden=item.id!=='terminal';detail.hidden=false;renderDetail();$('detailClose').focus({preventScroll:true});}
 function closeDetail(force=false){if($('detail').hidden||busy&&!force)return;$('detail').hidden=true;$('detailFrame').className='detail-frame';$('lockerItems').textContent='';const last=activeSpot;activeSpot=null;if(last){const b=$('hotspots').querySelector('[data-spot="'+last.id+'"]');b?.focus({preventScroll:true});}}
 function modalButton(label,detail,action,disabled=false,primary=false){const b=document.createElement('button');b.className=primary?'modal-action primary-action':'modal-action';b.disabled=busy||disabled;b.textContent=label;if(detail){const small=document.createElement('small');small.textContent=detail;b.append(small);}b.addEventListener('click',()=>run(action));$('detailActions').append(b);}
 function renderDetail(){if(!activeSpot||$('detail').hidden)return;const id=activeSpot.id,item=data[id],first=s.night===1;$('detailEyebrow').textContent=(s.house===3?(area==='corridor'?'TOWER CORRIDOR / ':'TOWER ROOM / '):s.house===2&&floor===2?'SECOND FLOOR / ':'FIRST PERSON / ')+'检视';$('detailTitle').textContent=s.house===3&&id==='bed'?'折叠床':s.house===3&&id==='window'?'高层防护窗':s.house===3&&id==='storage'?'封闭物资柜':item.title;$('detailText').textContent=s.house===3&&id==='bed'?'折叠床靠着暖灯。领取走廊投放、完成今日安排后，你可以关灯入睡。':s.house===3&&id==='window'?'加固玻璃将街道和丧尸压成很远的影子。密封条仍需要定期检查。':s.house===3&&id==='storage'?'柜中物资摆放整齐。室内储备有限，走廊投放柜每天会额外提供一份。':first&&item.first?item.first:item.day||item.first;$('detailCode').textContent='OBJECT / '+id.toUpperCase();$('detailCoordinate').textContent=Shelter.houses[s.house].name+(s.house===2?' · '+(floor===2?'二楼卧室':'一楼客厅'):s.house===3?' · '+(area==='corridor'?'公共走廊':'私人居室'):'');$('terminalHouse').textContent=Shelter.houses[s.house].name;$('terminalCoins').textContent=s.coins;$('terminalReserve').textContent=s.reserve;$('detailActions').replaceChildren();if(s.phase==='end'){if(Shelter.canRelocate(s)&&id==='terminal')modalButton('领取资格，进入大楼','第五夜后开放，无需补交金币。','relocate',false,true);if(id==='towerDoor')modalButton('进入公共走廊','回看物资投放柜和邻居的门。','corridor',false,true);if(id==='returnDoor')modalButton('回到自己的房间','关上钢门。','towerRoom',false,true);modalButton('重新开始第一章','从末日警报重新体验。','restart',false,!Shelter.canRelocate(s)&&id!=='towerDoor'&&id!=='returnDoor');return;}
 if(first){if(id==='door')modalButton(s.door?'木板已经卡牢':'把木板抵进门框',s.door?'门已加固。':'木板会滑入卡槽，挡住外面的撞击。','door',s.door,true);if(id==='window')modalButton(s.window?'窗框已加固':'扣紧窗栓并加固窗框',s.window?'窗户暂时安全。':'装上金属横挡，扣紧窗栓。','window',s.window,true);if(id==='supplies')modalButton(s.supplies?'抽屉已搜过':'拉开抽屉搜查',s.supplies?'已拿到一份食物。':'找出可以过夜的食物。','supplies',s.supplies,true);if(id==='bed')modalButton('关灯，试着入睡',s.door&&s.window&&s.supplies?'首夜保护生效。':'还需要加固门窗并找到食物。','sleep',!s.door||!s.window||!s.supplies,true);return;}
 if(id==='door')modalButton('出门','查看外部世界。','outside',false,true);
 if(id==='window')modalButton(s.house===3?'检查防护窗密封条':'再加固窗框','完整度 +20，今晚防护 +15；消耗今日行动。','prepare',!s.dream||s.action,true);
 if(id==='terminal'){if(s.house<3){const next=Shelter.houses[s.house+1],gate=next.minNight&&s.night<next.minNight?'第 '+next.minNight+' 天开放 · ':'';modalButton('升级为'+next.name,gate+next.cost+' 金币 · 完整度恢复，获得一份食物。','upgrade',!Shelter.canUpgrade(s),true);}if(!s.dream){modalButton('梦境：一盏暖灯','今晚金币 +12。','lamp');modalButton('梦境：紧闭的门','今晚防护 +15。','shield');}}
 if(id==='storage')modalButton('整理一份室内储备','食物 +1 · 库存 '+s.reserve+' · 消耗今日行动。','sort',!s.dream||s.action||s.reserve<1,true);
 if(id==='fire'||id==='workbench')modalButton('加固安全屋','完整度 +20，今晚防护 +15；消耗今日行动。','prepare',!s.dream||s.action,true);
 if(id==='bed')modalButton('关灯入睡',s.house===3&&s.dropDay!==s.night?'先去走廊领取今天的物资投放。':'消耗 1 份食物；结算金币与损耗。','sleep',!s.dream||!s.action||s.food<1||(s.house===3&&s.dropDay!==s.night),true);
 if(id==='stairs'||id==='sofa')modalButton('上楼看看','进入二楼卧室。','upstairs',false,true);
 if(id==='stairsDown')modalButton('回到一楼','返回客厅、壁炉与安居终端。','downstairs',false,true);
 if(id==='radio')modalButton('调整频率','收听城外残存的信号。','radio',false,true);
 if(id==='towerDoor')modalButton('进入公共走廊','去投放柜领取物资；邻居交流由你决定。','corridor',false,true);
 if(id==='returnDoor')modalButton('回到自己的房间','关上钢门，继续今天的安排。','towerRoom',false,true);
 if(id==='dropLocker')modalButton(s.dropDay===s.night?'今天的投放已领取':'打开物资投放柜',s.dropDay===s.night?'明天指示灯会再次亮起。':'食物 +1、滤芯 +1；不消耗今日行动。','claimDrop',s.dropDay===s.night,true);
 if(id==='neighborDoor'){modalButton(s.neighborMet?'你已经和邻居打过招呼':'按响邻居门铃',s.neighborMet?'可以继续保持距离。':'只听一句话，不会扣除资源。','contactNeighbor',s.neighborMet,true);modalButton('保持距离','今天不接触其他住户。','skipNeighbor');}
 if(id==='airFilter')modalButton('安装一枚新滤芯','滤芯 '+s.filters+' 枚 · 今晚防护 +30 · 消耗今日行动。','installFilter',!s.dream||s.action||s.filters<1,true);
 if(id==='elevator')modalButton('其他楼层尚未开放','这一章只探索自己的楼层。','none',true);
 }
 async function run(action){if(busy)return;if(action==='outside'){$('outsideNotice').hidden=false;$('outsideBack').focus();return;}if(action==='skipNeighbor'){closeDetail();return;}if(action==='restart'){restart();return;}if(action==='radio'){$('detailFrame').classList.add('scanning');$('detailText').textContent='沙沙声里传来一句“还有人吗？”接着，信号再次中断。';return;}if(action==='sleep'){if(Shelter.act(s,'sleep').ok)beginAssault();return;}if(['upstairs','downstairs','corridor','towerRoom'].includes(action)){busy=true;closeDetail(true);inspector.hide();const target=action==='upstairs'?'villa-upstairs-v1.jpg':action==='downstairs'?'villa-v1.jpg':action==='corridor'?'tower-corridor-v1.jpg':'tower-v2.jpg';$('nextRoom').src='assets/'+target;stage.classList.add('changing-floor');await wait(motion?620:100);if(action==='upstairs'||action==='downstairs')floor=action==='upstairs'?2:1;else area=action==='corridor'?'corridor':'room';stage.classList.remove('changing-floor');syncRoom();inspector.show();busy=false;render();return;}
 const result=Shelter.act(s,action);if(!result.ok)return;
 if(action==='upgrade'||action==='relocate'){busy=true;closeDetail(true);inspector.hide();try{await preload(Shelter.houses[result.state.house].image);$('nextRoom').src='assets/'+Shelter.houses[result.state.house].image;$('upgradeLabel').textContent=Shelter.houses[result.state.house].name+' · 建造中';stage.classList.add('upgrading');await wait(motion?2700:220);s=result.state;floor=1;area='room';stage.classList.remove('upgrading');$('upgradeLabel').textContent='';if(s.house===1)await sounds.setMusicSource('cabin-music.m4a');if(s.house===3)await sounds.setMusicSource('tower-music.m4a');syncRoom();toast((action==='relocate'?'迁入完成 · ':'升级完成 · ')+Shelter.houses[s.house].name);}catch(e){stage.classList.remove('upgrading');toast('房间图片未载入，金币没有扣除。请重试。');}inspector.show();busy=false;render();return;}
 busy=true;const frame=$('detailFrame');if(action==='door'){frame.classList.add('installing');await wait(motion?1350:170);s=result.state;room.src='assets/'+currentImage();$('detailAfter').src='assets/'+currentImage();frame.classList.remove('installing');frame.classList.add('installed');}
 else if(action==='window'){frame.classList.add('reinforcing');await wait(motion?1100:150);s=result.state;frame.classList.remove('reinforcing');frame.classList.add('secured');$('windowBarricade').hidden=false;}
 else if(action==='supplies'||action==='sort'){frame.classList.add('opening-drawer');await wait(motion?850:130);s=result.state;frame.classList.add('opened-drawer');}
 else if(action==='claimDrop'){frame.classList.add('opening-locker');await wait(motion?1050:150);s=result.state;$('lockerItems').textContent='食物 +1 · 滤芯 +1';frame.classList.remove('opening-locker');frame.classList.add('opened-locker');}
 else{frame.classList.add('scanning');await wait(motion?600:100);s=result.state;}
 busy=false;render();renderDetail();$('detailText').textContent=s.log;}
 $('enter').addEventListener('click',()=>{if(!opening)startOpening();else enterGame();});$('skip').addEventListener('click',enterGame);$('detailClose').addEventListener('click',()=>closeDetail());$('detail').addEventListener('click',e=>{if(e.target===$('detail'))closeDetail();});$('outsideBack').addEventListener('click',()=>{$('outsideNotice').hidden=true;$('detailClose').focus();});document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(!$('outsideNotice').hidden){$('outsideNotice').hidden=true;$('detailClose').focus();}else closeDetail();}});
 $('assaultBrace').addEventListener('click',()=>resolveAssaultBeat(true));$('assaultYield').addEventListener('click',()=>resolveAssaultBeat(false));document.addEventListener('visibilitychange',()=>{if(!assaultState)return;clearTimeout(assaultTimeout);if(!document.hidden&&!assaultState.resolving)showAssaultBeat();});
 $('endingLook').addEventListener('click',()=>{endingDismissed=true;renderEnding();inspector.show();});$('endingRestart').addEventListener('click',restart);
 $('music').addEventListener('click',()=>{sounds.setMusic(!sounds.music);$('music').textContent=sounds.music?'音乐：开启':'音乐：关闭';$('music').setAttribute('aria-pressed',String(sounds.music));});$('audioRetry').addEventListener('click',()=>{$('audioRetry').hidden=true;sounds.retry();});$('restart').addEventListener('click',()=>{if(!busy)restart();});
 function motionUI(){document.body.classList.toggle('still',!motion);$('motion').textContent=motion?'动态：开启':'动态：关闭';$('motion').setAttribute('aria-pressed',String(motion));if(assaultState&&!assaultState.resolving){clearTimeout(assaultTimeout);showAssaultBeat();}}$('motion').addEventListener('click',()=>{motion=!motion;if(!motion&&opening)finishFlash();motionUI();startMotion();});matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',e=>{motion=!e.matches;if(!motion&&opening)finishFlash();motionUI();startMotion();});
 function resize(){const dpr=Math.min(devicePixelRatio||1,2);canvas.width=stage.clientWidth*dpr;canvas.height=stage.clientHeight*dpr;const ratio=1672/941,iw=Math.min(stage.clientWidth,stage.clientHeight*ratio),ih=iw/ratio,ox=(stage.clientWidth-iw)/2,oy=(stage.clientHeight-ih)/2;const point=s.house===0?[.643,.05]:s.house===1?[.815,.35]:s.house===3?(area==='corridor'?[.28,.15]:[.38,.35]):floor===2?[.36,.29]:[.812,.46];stage.style.setProperty('--lamp-x',((ox+point[0]*iw)/stage.clientWidth*100)+'%');stage.style.setProperty('--lamp-y',((oy+point[1]*ih)/stage.clientHeight*100)+'%');inspector.refresh();if(assaultState)placeAssaultButton(assaultState.beats[assaultState.index].id);}new ResizeObserver(resize).observe(stage);
 function draw(t){frame=0;if(!entered||!motion||document.hidden){ctx.clearRect(0,0,canvas.width,canvas.height);return;}frame=requestAnimationFrame(draw);if(t-last<32)return;last=t;const w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);const iw=Math.min(w,h*1672/941),ih=iw*941/1672;ctx.save();ctx.translate((w-iw)/2,(h-ih)/2);ctx.scale(iw,ih);const seconds=t/1000;
 if((s.house===1||s.house===2)&&floor===1){const p=s.house===1?{x:.283,y:.526,width:.048,height:.086}:{x:.350,y:.611,width:.047,height:.057};ctx.save();ctx.beginPath();ctx.rect(p.x,p.y-p.height,p.width,p.height);ctx.clip();ctx.globalCompositeOperation='screen';for(let i=0;i<12;i++){const x=p.x+.003+i*p.width/13,y=p.y,height=p.height*(.35+.35*(.5+.5*Math.sin(seconds*(2+i*.1)+i))),drift=.003*Math.sin(seconds*3+i);const g=ctx.createLinearGradient(0,y,0,y-height);g.addColorStop(0,'#ffb34505');g.addColorStop(.3,'#ffd47a80');g.addColorStop(1,'#ff921500');ctx.fillStyle=g;ctx.beginPath();ctx.moveTo(x-.004,y);ctx.quadraticCurveTo(x-.007,y-height*.5,x+drift,y-height);ctx.quadraticCurveTo(x+.005,y-height*.3,x+.003,y);ctx.fill();}ctx.restore();}
 if(stage.classList.contains('upgrading'))for(let i=0;i<36;i++){const x=(seconds*.16+i*.027)%1,y=.15+(i*.171%.75);ctx.fillStyle='rgba(255,218,132,'+(.3+.4*Math.sin(seconds*4+i)**2)+')';ctx.beginPath();ctx.ellipse(x,y,.0012,.002,0,0,Math.PI*2);ctx.fill();}ctx.restore();}
 function startMotion(){cancelAnimationFrame(frame);frame=0;if(entered&&motion&&!document.hidden)frame=requestAnimationFrame(draw);else ctx.clearRect(0,0,canvas.width,canvas.height);}document.addEventListener('visibilitychange',startMotion);motionUI();if(entered){$('intro').hidden=true;document.documentElement.classList.add('game-playing');document.body.classList.add('playing');window.scrollTo(0,0);$('hud').hidden=false;$('console').hidden=false;$('roomNote').hidden=false;inspector.show();syncRoom();render();startMotion();const resumeSound=()=>{sounds.start();document.removeEventListener('pointerdown',resumeSound);document.removeEventListener('keydown',resumeSound);};document.addEventListener('pointerdown',resumeSound,{once:true});document.addEventListener('keydown',resumeSound,{once:true});}else render();
})();
